version: "3.9"

services:

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"   # UI / Query
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    networks: [otel]

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks: [otel]
    depends_on: [tempo]

  jaeger:
    image: jaegertracing/all-in-one:1.51
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
    networks: [otel]

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel/config.yaml"]
    volumes:
      - ./collector-config.yaml:/etc/otel/config.yaml
    networks: [otel]
    ports:
      - "4317:4317"     # gRPC
      - "4318:4318"     # HTTP


  government-service:
    build:
      context: ./rip-government-infrastructure
    image: government-service:latest
    container_name: government-service
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_RESOURCE_ATTRIBUTES: service.name=government-service
      OTEL_TRACES_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: none
      OTEL_SDK_DISABLED: "false"
    networks: [otel]

networks:
  otel:
    driver: bridge
